version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kpp_postgres
    restart: always
    environment:
      POSTGRES_DB: kpp
      POSTGRES_USER: kpp_user
      POSTGRES_PASSWORD: kpp_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U kpp_user -d kpp" ]
        interval: 5s
        timeout: 3s
        retries: 20

  adminer:
    image: adminer
    container_name: kpp_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: